<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$parentCss = $block->getParentCssClass() ? ' ' . $block->getParentCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
<div class="page-title-wrapper-parent <?= $block->escapeHtmlAttr($parentCss) ?>">
    <div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
        <?= $block->getChildHtml('page.back.button') ?>
        <h2 class="page-title"
            <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()) : ?>
                aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
            <?php endif; ?>>
            <?= /* @noEscape */ $titleHtml ?>
        </h2>
        <?= $block->getChildHtml() ?>
    </div>
</div>
<?php endif; ?>
