define([
    'js/lib/vanilla-plugin',
], function(JSComponent) {
    'use strict';

    /**
     * Main.js
     * @author Ciro Arcadio <ciro.arcadio@dnafactory.it>
     *     Main application component.
     *     Initializes the main application with the given configuration.
     */
    return JSComponent.extend({
        defaults:{
            _autogenerated: true,
            children: {
                "dom-wrapper": {
                    component: "js/lib/dom-listener"
                }
            }
        },
    });
});