<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<div class="block block-addresses-default col-md-6 col-12">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Default Addresses')) ?></strong></div>
    <div class="block-content">

        <?php if ($_pAddsses = $block->getDefaultBilling()) : ?>
            <div class="card mb-4 box-address-billing">
                <strong class="card-header">
                    <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
                </strong>
                <div class="card-body">
                    <p class="card-text">
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </p>
                </div>
                <div class="card-footer text-right">
                    <a class="action card-link" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <i class="icon-edit"></i>
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div class="card mb-4 box-billing-address">
                <strong class="card-header"><span><?= $block->escapeHtml(__('Default Billing Address')) ?></span></strong>
                <div class="card-body">
                    <p class="card-text"><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($_pAddsses = $block->getDefaultShipping()) : ?>
            <div class="card mb-4 box-address-shipping">
                <strong class="card-header">
                    <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
                </strong>
                <div class="card-body">
                    <p class="card-text">
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </p>
                </div>
                <div class="card-footer text-right">
                    <a class="action card-link" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <i class="icon-edit"></i>
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div class="box box-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
