<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>
<div class="block block-addresses-default col-md-6 col-12">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Additional Address Entries')) ?></strong>
    </div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>
            <?php $_counter = 0; ?>
            <?php foreach ($_pAddsses as $address) : ?>
                <?php $_counter++; ?>
                <div class="card mb-4 box-address-shipping">
                    <strong class="card-header">
                        <span><?= $block->escapeHtml(__('Address')) . ' ' . $_counter ?></span>
                    </strong>
                    <div class="card-body">
                        <p class="card-text">
                            <?= $block->escapeHtml($address->getFirstname()) . ' ' . $block->escapeHtml($address->getLastname()) ?> <br>
                            <?= $block->escapeHtml($block->getStreetAddress($address)) ?> <br>
                            <?= $block->escapeHtml($address->getRegion()->getRegion())  . ', ' . $block->escapeHtml($address->getCity())  . ', ' . $block->escapeHtml($address->getPostcode()) ?> <br>
                            <?= $block->escapeHtml($block->getCountryByCode($address->getCountryId())) ?> <br>
                            <?php
                                $phone = $block->escapeHtml($address->getTelephone());
                            ?>
                            T: <a href="tel:<?= $phone ?>"><?= $phone ?></a>
                        </p>
                    </div>
                    <div class="card-footer text-right">
                        <a class="action delete card-link" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>"><i class="icon-trash"></i></a>
                        <a class="action card-link" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"><i class="icon-edit"></i></a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else : ?>
            <div class="card mb-4 box-address-shipping">
                <strong class="card-header">
                    <span><?= $block->escapeHtml(__('No Address')) ?></span>
                </strong>
                <div class="card-body">
                    <p class="card-text empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
<div class="actions-toolbar col-12">
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>
<!--<div class="secondary col-12">
    <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
</div>-->

<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "td a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
