<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/**
 * @var $block \Amasty\Shopby\Block\Navigation\FilterCollapsing
 */
?>

<script type="text/x-magento-init">
    {
        ".sidebar #narrow-by-list": {
            "filterAccordion": {
                "multipleCollapsible": true,
                "openedState":"expanded",
                "active": [<?= $block->escapeHtml(implode(",", $block->getFiltersExpanded()))?>],
                "collapsible": true,
                "animate": 300,
                "collateral": {
                    "element": "#filter-menu",
                    "openedState": "sub-active"
                }
            }
        },
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "filter-layer": {
                        "component": "filterManager",
                        "config": {
                            "expandedClass": "",
                            "filtersContainer": "#filter-menu"
                        }
                    }
                }
            }
        }
    }
</script>
