<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="btn btn-link text-decoration-none p-0 d-md-none btn-sticky font-h5 ml-auto float-right"
        data-toggle="filters"
        data-mage-init='{ "sticky" : { "stickAfter": 180, "spacingTop": 280, "stickyClass":"_sticky btn-secondary pl-1 pr-2 py-1-5 text-white" } }'
        type="button" data-bind="scope: 'filter-layer'">
    <i class="icon-filter font-h1 mr-1"></i> <?= $block->escapeHtml(__('Filters')); ?>
    <!-- ko if: activeFiltersCount() > 0 -->
        <span class="count" data-bind="text: '('+ activeFiltersCount() + ')'"></span>
    <!-- /ko -->
</div>
<div class="clear-both"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "filter-layer": {
                        "component": "Amasty_Shopby/js/layer-state"
                    }
                }
            }
        }
    }
</script>
