<?php
/**
 * Effettua un override in caso di necessità
 */
/** @var \Magento\Framework\View\Element\Template $block */
?>
<link href="<?= $block->getViewFileUrl('fonts/DNAFactory-Theme-Icons/corona-radiata-icons.woff'); ?>" rel="preload" as="font" crossorigin />
<link href="<?= $block->getViewFileUrl('fonts/DNAFactory-Theme-Icons/corona-radiata-icons.woff2'); ?>" rel="preload" as="font" crossorigin />
