<?php

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}

$customCssClasses = $block->getCustomCss();
$iconClass = $block->getIconClass();

$label = $block->hasData('label')? $block->getData('label') : __('Sign Out');
?>
<li class="nav item <?= $customCssClasses ?>" data-label="<?= $block->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <?php if ($iconClass) : ?>
            <i class="<?= $iconClass ?>"></i>
        <?php endif; ?>
        <?= $block->escapeHtml($label) ?>
    </a>
</li>
