<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<?php
$showBackButton = false;
?>
<div class="form-wrapper-center row justify-content-center justify-content-lg-start">
    <form class="col col-sm-8 col-lg-6 form password forget"
          action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <legend class="legend"><span class="headline-4 color-black"><?= $block->escapeHtml(__('Recupera la tua Password')) ?></span></legend><br>
            <div class="field note no-label"><?= $block->escapeHtml(__('Inserisci il tuo indirizzo email di seguito. Riceverai un link per fare il reset della password.')) ?></div>
            <div class="field email required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="btn btn-block btn-primary submit"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
            </div>
            <?php if ($showBackButton) : ?>
                <div class="secondary">
                    <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                </div>
            <?php endif; ?>
        </div>
    </form>
</div>
