<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <div class="block block-dashboard-addresses">
            <div class="block-content">
                <div class="box box-newsletter">
                    <div class="box-title">
                        <span><?= $block->escapeHtml(__('Iscrizione Newsletter')) ?></span>
                    </div>
                    <div class="box-content">
                        <fieldset class="fieldset">
                            <?= $block->getBlockHtml('formkey') ?>
                            <p>
                                <?= $block->escapeHtml(__('Non sei iscritto alla newsletter. Clicca qui sotto per effettuare l\'iscrizione')) ?>
                            </p>
                            <div class="field choice">
                                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('Iscriviti alla nostra newsletter generale')) ?>"<?php if ($block->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                                <label for="subscription" class="label"><span><?= $block->escapeHtml(__('Iscriviti alla nostra newsletter generale')) ?></span></label>
                            </div>
                            <?php /* Extensions placeholder */ ?>
                            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
                        </fieldset>
                    </div>
                    <div class="box-actions">
                        <div><button type="submit" title="<?= $block->escapeHtmlAttr(__('Salva')) ?>" class="action save btn btn-md btn-primary btn-round"><span><?= $block->escapeHtml(__('Salva')) ?></span></button></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="secondary"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
