<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<?php
$showPasswordStrengthIndicator = $block->getPasswordStrengthIndicatorDisplay();
?>
<div class="form-wrapper-center row">
    <form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
          method="post"
        <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
          id="form-validate"
          class="col-12 col-sm-12 col-md-8 col-lg-6 form password reset"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <legend class="legend"><span class="headline-4 color-black"><?= $block->escapeHtml(__('Informazioni Acesso')) ?></span></legend><br>
            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                <label class="label" for="password"><span><?= $block->escapeHtml(__('Nuova Password')) ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <div for="password" class="dna-field-info" id="password-info"><?= $block->escapeHtml(__('Inserisci una password di minimo 6 caratteri, di cui almeno una lettera e un numero')) ?></div>
                    <?php if ($showPasswordStrengthIndicator) : ?>
                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="field confirmation required">
                <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Conferma Password')) ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div>
                <button type="submit" class="btn btn-block btn-primary submit"><span><?= $block->escapeHtml(__('Reset Password')) ?></span></button>
            </div>
        </div>
    </form>
</div>
