<?php
/** @var \Magento\Directory\Block\Currency $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "currency-manager": {
                    "component": "Magento_Directory/js/currency-data",
                    "config": {}
                }
            }
        }
    }
}
</script>
